ViewOrdersBundle\Entity\Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'наименование товара'
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            options:
                comment: 'цена товара'
        dateCreate:
            type: datetime
            nullable: false
            options:
                comment: 'дата добавления товара'
#               default: CURRENT_TIMESTAMP
            column: date_create
        dateUpdate:
            type: datetime
            nullable: false
            options:
                comment: 'дата обновления'
#               default: CURRENT_TIMESTAMP
            column: date_update
    lifecycleCallbacks: 
        prePersist: [setDateCreateValue, setDateUpdateValue]
        preUpdate: [setDateUpdateValue]
