view_orders:
    resource: "@ViewOrdersBundle/Resources/config/routing.yml"
    prefix:   /

show_orders:
    resource: "@ShowOrdersBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
