products_index:
    path:     /
    defaults: { _controller: "ViewOrdersBundle:Products:index" }
    methods:  GET

products_show:
    path:     /{id}/show
    defaults: { _controller: "ViewOrdersBundle:Products:show" }
    methods:  GET

products_new:
    path:     /new
    defaults: { _controller: "ViewOrdersBundle:Products:new" }
    methods:  [GET, POST]

products_edit:
    path:     /{id}/edit
    defaults: { _controller: "ViewOrdersBundle:Products:edit" }
    methods:  [GET, POST]

products_delete:
    path:     /{id}/delete
    defaults: { _controller: "ViewOrdersBundle:Products:delete" }
    methods:  DELETE
