ShowOrdersBundle\Entity\Customers:
    type: entity
    table: customers
    indexes:
        lastname_name:
            columns:
                - lastname
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                comment: имя
        lastname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
                comment: фамилия
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'эл. почта'
        dateCreate:
            type: datetime
            nullable: false
            options:
                comment: 'дата добавления пользователя'
                default: CURRENT_TIMESTAMP
            column: date_create
    lifecycleCallbacks: {  }
    oneToMany: 
        orders:
            targetEntity: Customers
            mappedBy: orders
